# Generated by Django 4.1.5 on 2023-05-18 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorija',
            options={'ordering': ('ime',), 'verbose_name': 'kategorija', 'verbose_name_plural': 'kategorije'},
        ),
        migrations.AlterModelOptions(
            name='proizvod',
            options={'ordering': ('imeproizvoda',), 'verbose_name': 'proizvod', 'verbose_name_plural': 'proizvodi'},
        ),
    ]
