# Generated by Django 4.1.5 on 2023-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_proizvod_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='slika',
            field=models.ImageField(blank=True, default='greska/error.jpg', null=True, upload_to='proizvod'),
        ),
    ]
