# Generated by Django 4.1.5 on 2023-05-21 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_proizvod_slika'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korpa_id', models.CharField(blank=True, max_length=150)),
                ('datum_dodavanja', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Korpa',
                'ordering': ['datum_dodavanja'],
            },
        ),
        migrations.CreateModel(
            name='KorpaProizvodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('aktivno', models.BooleanField(default=True)),
                ('korpa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.korpa')),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.proizvod')),
            ],
            options={
                'db_table': 'KorpaProizvodi',
            },
        ),
    ]
