# Generated by Django 4.1.5 on 2023-05-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_naruzba_naruzbaproizvodi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Naruzba',
            new_name='Narudzba',
        ),
        migrations.RenameModel(
            old_name='NaruzbaProizvodi',
            new_name='NarudzbaProizvodi',
        ),
        migrations.AlterModelTable(
            name='narudzba',
            table='Narudzba',
        ),
        migrations.AlterModelTable(
            name='narudzbaproizvodi',
            table='NarudzbaProizvodi',
        ),
    ]
