# Generated by Django 4.1.5 on 2023-05-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_naruzba_narudzba_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narudzba',
            old_name='adresazanaplatu1',
            new_name='billingAddress1',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='adresazaslanje1',
            new_name='billingCity',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='drzavazaslanje',
            new_name='billingCountry',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='gradzanaplatu',
            new_name='billingName',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='gradzaslanje',
            new_name='billingPostcode',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='imenaplate',
            new_name='shippingAddress1',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='imezaslanje',
            new_name='shippingCity',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='postanskikod',
            new_name='shippingCountry',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='postanskikodzaslanje',
            new_name='shippingName',
        ),
        migrations.RenameField(
            model_name='narudzba',
            old_name='zemljanaplate',
            new_name='shippingPostcode',
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Email Address'),
        ),
    ]
