# Generated by Django 4.1.5 on 2023-05-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_adresazanaplatu1_narudzba_billingaddress1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narudzba',
            old_name='ukupno',
            new_name='total',
        ),
    ]
