# Generated by Django 4.1.5 on 2023-05-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_ukupno_narudzba_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narudzbaproizvodi',
            old_name='naruzba',
            new_name='narudzba',
        ),
    ]
