# Generated by Django 4.1.5 on 2023-05-27 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_rename_naruzba_narudzbaproizvodi_narudzba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narudzba',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='KM ukupno'),
        ),
        migrations.CreateModel(
            name='pregled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kontekst', models.CharField(max_length=550)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.proizvod')),
            ],
        ),
    ]
