# Generated by Django 4.1.5 on 2023-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_narudzba_total_pregled'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontaktPoruka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('poruka', models.TextField()),
            ],
        ),
    ]
